# Generated by Django 2.2.3 on 2019-07-02 18:41

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, default='', max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, default='', max_length=30, verbose_name='last name')),
                ('phone_number', models.CharField(blank=True, default='', max_length=30, verbose_name='phone number')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('birth_date', models.DateField()),
            ],
        ),
    ]
